version: 'Build {build}'

skip_tags: true

image: Visual Studio 2017
configuration: Release
platform: Any CPU

cache:
  - packages -> **\packages.config

before_build:
- ps: >-
    $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
    
    ($env:APPVEYOR_REPO_NAME) >> VERSION
    
    ($env:APPVEYOR_REPO_BRANCH) >> VERSION
    
    ($env:GIT_HASH) >> VERSION
    
    ($env:APPVEYOR_BUILD_VERSION) >> VERSION
    
    ($env:APPVEYOR_REPO_COMMIT_TIMESTAMP) >> VERSION
    
- appveyor-retry nuget restore

build:
  project: XIVLauncher.sln
  verbosity: minimal