name: Build XIVLauncher
on: [push, pull_request]
concurrency: build_xl

jobs:
  build-release:
    name: Build Release on Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: write # Must be 'write' to create a release
      attestations: write
    steps:
#      - uses: nadock/verified_commits_check@f9b330e987c2e7121dfc0230e65cb5751ee5fac9
      - uses: actions/checkout@v1
      - name: Initialize Submodules
        run: git submodule update --init --recursive
      - name: Install VPK
        run: |
          dotnet tool install -g vpk
      - name: Publish XIVLauncher
        run: |
          cd src/XIVLauncher
          dotnet publish --self-contained -r win-x64 -o publish
      - name: Publish XIVLauncher.Patcher
        run: |
          cd src/XIVLauncher.PatchInstaller
          dotnet publish --self-contained -r win-x64 -o ../XIVLauncher/publish/patcher
      - name: Generate Hashes File
        run: ./scripts/CreateHashList.ps1 ./src/XIVLauncher/publish
      - name: Attest Artifacts
        if: ${{ github.repository_owner == 'goatcorp' && github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            src/XIVLauncher/publish/XIVLauncher.exe
            src/XIVLauncher/publish/XIVLauncher.*.dll
            src/XIVLauncher/publish/XIVLauncher.*.exe
            src/XIVLauncher/publish/hashes.json
      - name: Build Velopack Release
        id: build-velopack
        run: |
          cd src/XIVLauncher
          $releases = Invoke-WebRequest -Uri 'https://api.github.com/repos/goatcorp/FFXIVQuickLauncher/releases'
          $current = ConvertFrom-Json -InputObject $releases.Content | Select-Object -First 1
          $refver = $env:GITHUB_REF -replace '.*/'
          echo "::set-output name=version::$refver"
          mkdir Releases
          cp .\Resources\CHANGELOG.txt .\Releases\
          $release_file = $current.assets | Where-Object -Property name -Value RELEASES -EQ
          Invoke-WebRequest -Uri $release_file.browser_download_url -OutFile .\Releases\RELEASES
          $delta_file = $current.assets | Where-Object -Property name -Value "*delta.nupkg" -Like
          Invoke-WebRequest -Uri $delta_file.browser_download_url -OutFile ".\Releases\$($delta_file.name)"
          $full_file = $current.assets | Where-Object -Property name -Value "*full.nupkg" -Like
          Invoke-WebRequest -Uri $full_file.browser_download_url -OutFile ".\Releases\$($full_file.name)"
          vpk pack -u XIVLauncher -v $refver -p .\publish\ -e XIVLauncher.exe -i .\Resources\dalamud_icon.ico --noPortable
          Start-Sleep -s 10
          rm ".\Releases\$($delta_file.name)"
          rm ".\Releases\$($full_file.name)"
      - name: Attest Setup
        if: ${{ github.repository_owner == 'goatcorp' && github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            src/XIVLauncher/Releases/*.exe
            src/XIVLauncher/Releases/*.nupkg
            src/XIVLauncher/Releases/RELEASES
            src/XIVLauncher/Releases/releases.win.json
            src/XIVLauncher/Releases/assets.win.json
      - name: Upload release assets
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./src/XIVLauncher/Releases/**
          name: Release ${{ steps.build-velopack.outputs.version }}
          body_path:  RELEASE.md
          draft: true
          prerelease: true
      - name: Publish release
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: true

      # Disabled, file too large now that we're doing self-contained
      #- name: VirusTotal Scan
      #  uses: crazy-max/ghaction-virustotal@a3f74cfd584b0658320aec5e94ab6a8d16dca05f
      #  with:
      #    vt_api_key: ${{ secrets.VT_API_KEY }}
      #    files: ./src/XIVLauncher/Releases/*.exe

  build:
    name: Build on Windows
    runs-on: windows-2022
    if: "!startsWith(github.ref, 'refs/tags/')"
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Submodules
        run: git submodule update --init --recursive
      - name: Publish XIVLauncher
        run: |
          cd src/XIVLauncher
          dotnet publish --self-contained -r win-x64 -o publish
      - name: Publish XIVLauncher.Patcher
        run: |
          cd src/XIVLauncher.PatchInstaller
          dotnet publish --self-contained -r win-x64 -o ../XIVLauncher/publish/patcher
      - name: Generate Hashes File
        run: ./scripts/CreateHashList.ps1 ./src/XIVLauncher/publish/
      - name: Attest Artifacts
        if: ${{ github.repository_owner == 'goatcorp' && github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            src/XIVLauncher/publish/XIVLauncher.exe
            src/XIVLauncher/publish/XIVLauncher.*.dll
            src/XIVLauncher/publish/XIVLauncher.*.exe
            src/XIVLauncher/publish/hashes.json
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: xivlauncher-artifact
          path: src/XIVLauncher/publish/
