name: Update localization

on:
  workflow_dispatch:
  
jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update localization
      uses: crowdin/github-action@1.1.0
      with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          export_only_approved: true
          push_translations: true
          commit_message: 'Update localization'
          create_pull_request: true
          pull_request_title: 'Update localization'
          pull_request_body: 'Update localization with latest translations from crowdin'
          config: '.github/crowdin.yml'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CROWDIN_PROJECT_ID: ${{secrets.CROWDIN_PROJECT_ID}}
        CROWDIN_PERSONAL_TOKEN: ${{secrets.CROWDIN_PERSONAL_TOKEN}}
